Fix libc errno returns
Lind-Project/Lind-GlibC pull request #79
Opened 2023-10-11 18:28 UTC by Yaxuan-w

## Description

Fixes [#317](https://github.com/Lind-Project/lind_project/issues/317)
 

### Type of change

Fixed problems with return values especially when syscall failed (errno related).
- shmdt
- munmap
- mprotect

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Corresponding test are in branch `test-sigprocmask` in `Lind-Project/tests/testcases`, and in format: testX.c for test of X.

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-project, safeposix-rust)

2023-10-15 23:02 UTC, rennergade commented
Did you run the test suites on this?

2023-10-16 13:36 UTC, yizhuoliang commented
Make sense, neg signs are never need when return a call to another syscall, they are needed only when you set the errorno

2023-10-16 17:29 UTC, Yaxuan-w commented
> Did you run the test suites on this?

Yes, it passes all test cases in /lind_project

2023-10-17 19:51 UTC, RusherRG approved these changes
The changes look self-explanatory. We are returning -1 for errors and 0 otherwise and setting the errno accordingly. :v:

2023-10-17 19:51 UTC, RusherRG commented on configure.new
I think you committed it by mistake. Can you remove this file?

2023-10-17 19:52 UTC, RusherRG requested changes

2023-10-17 19:52 UTC, RusherRG commented on configure.new
I think you pushed this by mistake. Can you remove this file?

2023-10-19 04:32 UTC, rennergade commented on configure.new
@Yaxuan-w alice it looks like you added this by mistake, can you remove? then i think this can be merged

2023-10-19 09:13 UTC, Yaxuan-w commented on configure.new
Thanks for pointing out!

2023-10-19 17:21 UTC, merged