Adding sync_file_range Syscall
Lind-Project/Lind-GlibC pull request #82
Opened 2023-12-08 14:26 UTC by kuzeyardabulut

2023-12-08 20:17 UTC, rennergade commented on sysdeps/nacl/sysdep.h
> + int rv = __nacl_irt_sync_file_range (fd, offset, nbytes, flags);
weird spacing here too

2023-12-08 20:17 UTC, rennergade requested changes
Some nitpicks about whitespace. Content looks good.

2023-12-08 21:12 UTC, RusherRG approved these changes
Apart from the formatting changes suggested by @rennergade, everything else looks good.

2023-12-09 00:09 UTC, justyoyo123 approved these changes
This looks good to me.

2023-12-15 04:41 UTC, merged